# Use an official MySQL runtime as a parent image
FROM mysql:latest

# Environment variables to configure MySQL
ENV MYSQL_ROOT_PASSWORD=root_password
ENV MYSQL_DATABASE=my_database
ENV MYSQL_USER=my_user
ENV MYSQL_PASSWORD=my_password


# Expose port (optional, MySQL default is 3306)
EXPOSE 3306
